version: '3.7'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      TZ: America/Bogota
      PGTZ: America/Bogota
      POSTGRES_DATABASE: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - ./container/postgres:/var/lib/postgresql/data